name: Clean up workflow runs

on:
  schedule:
    - cron: '0 23 * * *'  # Daily at 23:00 UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Delete all workflow runs (with pagination)
      run: |
        page=1
        while true; do
          echo "Fetching page $page ..."
          runs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100&page=$page" \
              | jq -r '.workflow_runs[].id')

          if [ -z "$runs" ]; then
            echo "No more runs found, cleanup finished."
            break
          fi

          for run_id in $runs; do
            echo "Deleting run: $run_id"
            curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
          done

          page=$((page+1))
        done
