name: Schedule Management

on:
  schedule:
    # All schedules now follow: schedule > keyword > article > image > deploy > index (10x daily)
    - cron: '0 0 * * *'    # 00:00 UTC - full workflow with keywords
    - cron: '24 2 * * *'   # 02:24 UTC - full workflow with keywords
    - cron: '48 4 * * *'   # 04:48 UTC - full workflow with keywords
    - cron: '12 7 * * *'   # 07:12 UTC - full workflow with keywords
    - cron: '36 9 * * *'   # 09:36 UTC - full workflow with keywords
    - cron: '0 12 * * *'   # 12:00 UTC - full workflow with keywords
    - cron: '24 14 * * *'  # 14:24 UTC - full workflow with keywords
    - cron: '48 16 * * *'  # 16:48 UTC - full workflow with keywords
    - cron: '12 19 * * *'  # 19:12 UTC - full workflow with keywords
    - cron: '36 21 * * *'  # 21:36 UTC - full workflow with keywords
    
  workflow_dispatch:
    inputs:
      workflow_type:
        description: 'Select workflow pattern to run'
        required: true
        default: 'full'
        type: choice
        options:
          - 'full'        # keyword > article > image > deploy > index
          - 'articles'    # article > image > deploy > index
          - 'keywords'    # keywords only
          - 'deploy'      # deploy > index only

concurrency:
  group: schedule-management-${{ github.ref }}
  cancel-in-progress: false

jobs:
  determine-workflow:
    runs-on: ubuntu-latest
    outputs:
      workflow_type: ${{ steps.determine.outputs.workflow_type }}
      run_keywords: ${{ steps.determine.outputs.run_keywords }}
      
    steps:
      - name: Determine workflow type
        id: determine
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # Manual trigger - use selected option
            WORKFLOW_TYPE="${{ github.event.inputs.workflow_type }}"
          else
            # All scheduled triggers now run full workflow (keyword > article > image > deploy > index)
            CURRENT_HOUR=$(date +%H)
            CURRENT_MINUTE=$(date +%M)
            
            # All scheduled times run full workflow with keywords
            if [[ ("$CURRENT_HOUR" == "00" && "$CURRENT_MINUTE" == "00") || \
                  ("$CURRENT_HOUR" == "02" && "$CURRENT_MINUTE" == "24") || \
                  ("$CURRENT_HOUR" == "04" && "$CURRENT_MINUTE" == "48") || \
                  ("$CURRENT_HOUR" == "07" && "$CURRENT_MINUTE" == "12") || \
                  ("$CURRENT_HOUR" == "09" && "$CURRENT_MINUTE" == "36") || \
                  ("$CURRENT_HOUR" == "12" && "$CURRENT_MINUTE" == "00") || \
                  ("$CURRENT_HOUR" == "14" && "$CURRENT_MINUTE" == "24") || \
                  ("$CURRENT_HOUR" == "16" && "$CURRENT_MINUTE" == "48") || \
                  ("$CURRENT_HOUR" == "19" && "$CURRENT_MINUTE" == "12") || \
                  ("$CURRENT_HOUR" == "21" && "$CURRENT_MINUTE" == "36") ]]; then
              WORKFLOW_TYPE="full"
            else
              # Fallback to full workflow for any unmatched scheduled time
              WORKFLOW_TYPE="full"
            fi
          fi
          
          echo "workflow_type=$WORKFLOW_TYPE" >> $GITHUB_OUTPUT
          
          # Determine if keywords should run
          if [[ "$WORKFLOW_TYPE" == "full" || "$WORKFLOW_TYPE" == "keywords" ]]; then
            echo "run_keywords=true" >> $GITHUB_OUTPUT
          else
            echo "run_keywords=false" >> $GITHUB_OUTPUT
          fi
          
          echo "=== Workflow Determination ==="
          echo "Event: ${{ github.event_name }}"
          echo "Workflow Type: $WORKFLOW_TYPE"
          echo "Run Keywords: $(if [[ "$WORKFLOW_TYPE" == "full" || "$WORKFLOW_TYPE" == "keywords" ]]; then echo "true"; else echo "false"; fi)"

  trigger-keywords:
    needs: determine-workflow
    if: needs.determine-workflow.outputs.run_keywords == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger keywords generation
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-keywords-generation
          client-payload: |
            {
              "scheduled_trigger": true,
              "workflow_type": "${{ needs.determine-workflow.outputs.workflow_type }}",
              "source": "schedule"
            }

  trigger-articles-direct:
    needs: determine-workflow
    if: needs.determine-workflow.outputs.workflow_type == 'articles'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger articles generation directly
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-articles-generation
          client-payload: |
            {
              "scheduled_trigger": true,
              "workflow_type": "articles",
              "source": "schedule-direct"
            }

  trigger-deploy-only:
    needs: determine-workflow
    if: needs.determine-workflow.outputs.workflow_type == 'deploy'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Hugo deploy directly
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-hugo-deploy
          client-payload: |
            {
              "scheduled_trigger": true,
              "workflow_type": "deploy",
              "source": "schedule-direct"
            }
